### ISSUE TITLE
Cannot find sun.net.www.protocol.file.FileURLConnection

### ISSUE THREAD

**Issue by yinwang0** [yinwang0/pysonar2#116]
The part that's copying the model files (without running from jar build) is using sun.net.www.protocol.file.FileURLConnection. But this thing seems to be outdated at some point. So if run 'mvn pacakge' without -DskipTests, it will try to use sun.net.www.protocol.file.FileURLConnection and thus fail.

I haven't yet found a replacement of sun.net.www.protocol.file.FileURLConnection from search. This is a piece of copied exmaple code, so I don't really know how it works ;)

Thanks to anybody who knows how to fix this.

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.yinwang.pysonar.TestRefs
Verifying tests:
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.184 sec <<< FAILURE!
testRefs(org.yinwang.pysonar.TestRefs)  Time elapsed: 0.14 sec  <<< ERROR!
java.lang.IllegalAccessError: class org.yinwang.pysonar.$ (in unnamed module @0x4d18685a) cannot access class sun.net.www.protocol.file.FileURLConnection (in module java.base) because module java.base does not export sun.net.www.protocol.file to unnamed module @0x4d18685a
	at org.yinwang.pysonar.$.copyResourcesRecursively($.java:200)
	at org.yinwang.pysonar.Analyzer.copyModels(Analyzer.java:141)
	at org.yinwang.pysonar.Analyzer.<init>(Analyzer.java:71)
...

**Comment by yinwang0** [comment]
Found solution at https://github.com/playframework/playframework/issues/10883. Fixing..
